sudo: required
services:
  - docker

before_install:
  - docker build -t tomizrad/docker-react -f Dockerfile.dev ./

##Ensures the script doesn't wait for user interaction##
script:
  - docker run tomizrad/docker-react npm run test -- --coverage